services:
  cashflow-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SECRET=dev-secret-key
      - BASE_URL=http://localhost:3000
