services:
  postgres:
    image: postgres:16
    user: 1000:1000
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./__data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
